//! Tauri application library root.
//!
//! This module wires together:
//!   - The [`daemon`] module — sidecar lifecycle and IPC router.
//!   - The [`commands`] module — `#[tauri::command]` handlers exposed to the
//!     WebView front-end.
//!   - Plugin registration (shell for sidecar, global-shortcut).
//!
//! The `run()` function is called from `main.rs` (and from the mobile entry
//! points generated by Tauri's build system on iOS/Android).

mod commands;
mod daemon;

use std::sync::Arc;
use tauri::Manager;
use tauri::menu::{MenuBuilder, MenuItemBuilder};
use tauri::tray::TrayIconBuilder;
use tracing::info;
use tracing_subscriber::{fmt, EnvFilter};
use tauri_plugin_global_shortcut::{Code, Modifiers, Shortcut, ShortcutState};

pub fn run() {
    // -----------------------------------------------------------------------
    // Initialise tracing for the host process.
    // The daemon has its own tracing instance on the other end of the pipe.
    // -----------------------------------------------------------------------
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new("crumbs_tauri=info,warn"));

    fmt::Subscriber::builder()
        .with_env_filter(filter)
        .with_writer(std::io::stderr)
        .with_target(true)
        .init();

    info!("Crumbs Tauri host starting");

    tauri::Builder::default()
        // -------------------------------------------------------------------
        // Shell plugin — required to spawn the daemon sidecar.
        // -------------------------------------------------------------------
        .plugin(tauri_plugin_shell::init())
        // -------------------------------------------------------------------
        // Dialog plugin — required for native folder picker dialogs.
        // -------------------------------------------------------------------
        .plugin(tauri_plugin_dialog::init())
        // -------------------------------------------------------------------
        // Global shortcut plugin — for the quick-open hotkey (Phase 2 UI).
        // -------------------------------------------------------------------
        .plugin({
            let ctrl_shift_space = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::Space);
            tauri_plugin_global_shortcut::Builder::new()
                .with_shortcut(ctrl_shift_space)
                .unwrap()
                .with_handler(move |app, shortcut, event| {
                    if event.state == ShortcutState::Pressed && shortcut == &ctrl_shift_space {
                        info!("Ctrl+Shift+Space shortcut pressed!");
                        if let Some(window) = app.get_webview_window("search") {
                            if window.is_visible().unwrap_or(false) {
                                window.hide().unwrap();
                            } else {
                                window.show().unwrap();
                                window.set_focus().unwrap();
                            }
                        }
                    }
                })
                .build()
        })
        // -------------------------------------------------------------------
        // Setup hook: launch the daemon before the first window opens.
        // -------------------------------------------------------------------
        .setup(|app| {
            info!("Tauri app reached the setup phase!");
            
            // 1. Create menu items for the system tray
            let open_search = MenuItemBuilder::with_id("open_search", "Open Search").build(app)?;
            let settings_dashboard = MenuItemBuilder::with_id("settings_dashboard", "Settings Dashboard").build(app)?;
            let quit = MenuItemBuilder::with_id("quit", "Quit").build(app)?;
            
            // 2. Build the menu
            let menu = MenuBuilder::new(app)
                .items(&[&open_search, &settings_dashboard, &quit])
                .build()?;

            // 3. Build the tray with the event handler
            let mut tray_builder = TrayIconBuilder::new()
                .menu(&menu)
                .on_menu_event(|app, event| {
                    match event.id().as_ref() {
                        "open_search" => {
                            if let Some(window) = app.get_webview_window("search") {
                                window.show().unwrap();
                                window.set_focus().unwrap();
                            }
                        }
                        "settings_dashboard" => {
                            if let Some(window) = app.get_webview_window("settings") {
                                window.show().unwrap();
                                window.set_focus().unwrap();
                            }
                        }
                        "quit" => {
                            info!("Quit requested via tray menu. Cleaning up daemon...");
                            if let Some(daemon_handle) = app.try_state::<Arc<crate::daemon::DaemonHandle>>() {
                                if let Ok(mut child_lock) = daemon_handle.child.try_lock() {
                                    if let Some(child) = child_lock.take() {
                                        let _ = child.kill();
                                    }
                                }
                            }
                            app.exit(0);
                        }
                        _ => {}
                    }
                });

            if let Some(icon) = app.default_window_icon() {
                tray_builder = tray_builder.icon(icon.clone());
            }

            let _tray = tray_builder.build(app)?;

            let handle = app.handle().clone();
            // `daemon::launch` is async, so we spawn a Tokio task.
            // The Tauri runtime provides a Tokio executor when using
            // `tauri::async_runtime`.
            tauri::async_runtime::spawn(async move {
                if let Err(e) = daemon::launch(handle).await {
                    tracing::error!(error = %e, "daemon launch failed");
                }
            });
            Ok(())
        })
        .on_window_event(|window, event| match event {
            tauri::WindowEvent::CloseRequested { api, .. } => {
                if window.label() == "settings" {
                    api.prevent_close();
                    window.hide().unwrap();
                }
            }
            _ => {}
        })
        // -------------------------------------------------------------------
        // Register all front-end–callable commands.
        // -------------------------------------------------------------------
        .invoke_handler(tauri::generate_handler![
            commands::search,
            commands::status,
            commands::reindex,
            commands::open_file,
            commands::update_engine_config,
            commands::get_onboarding_status,
            commands::update_monitored_folders,
            commands::select_folders_dialog,
            commands::list_indexed_files,
            commands::download_models,
            commands::check_models_exist,
            commands::start_model_download,
        ])
        .run(tauri::generate_context!())
        .expect("error while running Tauri application");
}
