//! Tauri application library root.
//!
//! This module wires together:
//!   - The [`daemon`] module — sidecar lifecycle and IPC router.
//!   - The [`commands`] module — `#[tauri::command]` handlers exposed to the
//!     WebView front-end.
//!   - Plugin registration (shell for sidecar, global-shortcut).
//!
//! The `run()` function is called from `main.rs` (and from the mobile entry
//! points generated by Tauri's build system on iOS/Android).

mod commands;
mod daemon;

use tauri::Manager;
use tracing::info;
use tracing_subscriber::{fmt, EnvFilter};
use tauri_plugin_global_shortcut::{Code, Modifiers, Shortcut, ShortcutState};

pub fn run() {
    // -----------------------------------------------------------------------
    // Initialise tracing for the host process.
    // The daemon has its own tracing instance on the other end of the pipe.
    // -----------------------------------------------------------------------
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new("crumbs_tauri=info,warn"));

    fmt::Subscriber::builder()
        .with_env_filter(filter)
        .with_writer(std::io::stderr)
        .with_target(true)
        .init();

    info!("Crumbs Tauri host starting");

    tauri::Builder::default()
        // -------------------------------------------------------------------
        // Shell plugin — required to spawn the daemon sidecar.
        // -------------------------------------------------------------------
        .plugin(tauri_plugin_shell::init())
        // -------------------------------------------------------------------
        // Global shortcut plugin — for the quick-open hotkey (Phase 2 UI).
        // -------------------------------------------------------------------
        .plugin({
            let ctrl_shift_space = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::Space);
            tauri_plugin_global_shortcut::Builder::new()
                .with_shortcut(ctrl_shift_space)
                .unwrap()
                .with_handler(move |app, shortcut, event| {
                    if event.state == ShortcutState::Pressed && shortcut == &ctrl_shift_space {
                        info!("Ctrl+Shift+Space shortcut pressed!");
                        if let Some(window) = app.get_webview_window("main") {
                            if window.is_visible().unwrap_or(false) {
                                window.hide().unwrap();
                            } else {
                                window.show().unwrap();
                                window.set_focus().unwrap();
                            }
                        }
                    }
                })
                .build()
        })
        // -------------------------------------------------------------------
        // Setup hook: launch the daemon before the first window opens.
        // -------------------------------------------------------------------
        .setup(|app| {
            info!("Tauri app reached the setup phase!");
            let handle = app.handle().clone();
            // `daemon::launch` is async, so we spawn a Tokio task.
            // The Tauri runtime provides a Tokio executor when using
            // `tauri::async_runtime`.
            tauri::async_runtime::spawn(async move {
                if let Err(e) = daemon::launch(handle).await {
                    tracing::error!(error = %e, "daemon launch failed");
                }
            });
            Ok(())
        })
        // -------------------------------------------------------------------
        // Register all front-end–callable commands.
        // -------------------------------------------------------------------
        .invoke_handler(tauri::generate_handler![
            commands::search,
            commands::status,
            commands::reindex,
            commands::open_file,
            commands::update_engine_config,
        ])
        .run(tauri::generate_context!())
        .expect("error while running Tauri application");
}
